version: '3.7'
services:
  postgresql_db:
    image: postgres:14
    restart: always
    volumes:
      - ./depixen-volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5439:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=depixen-pass
  app:
    container_name: api
    build: ./api
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - postgresql_db
    links:
      - postgresql_db
  react:
    build: ./my-app
    container_name: REACT
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true